language: csharp
solution: unflash.sln

jobs:
  include:
    - mono: latest

install:
 - nuget restore $TRAVIS_BUILD_DIR/unflash.sln

before_script:
 - msbuild /p:Configuration=Release /p:Platform=x86 $TRAVIS_BUILD_DIR/unflash.sln

script:
 - mono $TRAVIS_BUILD_DIR/unflash/bin/Release/unflash.exe

notifications:
  email:
    on_success: change
    on_failure: always
